In [1]:
import numpy as np
i = np.array([10, 20, 30, 40, 50])
print(i.dtype)

int32


In [2]:
import numpy as np
i = np.array([10.10, 20.20, 30.30])
i1 = i.astype('i')
print(i1)
print(i1.dtype)
print(i)

[10 20 30]
int32
[10.1 20.2 30.3]


In [3]:
import numpy as np
i = np.array([10, 20, 30])
i1 = i.astype('f')
print(i1)
print(i1.dtype)

[10. 20. 30.]
float32


In [4]:
import numpy as np
i = np.array([10.10, 20.20, 30.30])
i1 = i.astype(int)
print(i1)
print(i1.dtype)

[10 20 30]
int32


In [5]:
import numpy as np
i = np.array([10.10, 0, 30, 5, 23.25, 0, 0])
i1 = i.astype(bool)
print(i1)
print(i1.dtype)

[ True False  True  True  True False False]
bool
